import { SignInButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const { user, isLoaded, isSignedIn } = useUser();

  if (!isLoaded) return <div>Loading...</div>;

  return (
    <>
      <Head>
        <title>Clerk Endpoint</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Clerk <span className="text-[hsl(280,100%,70%)]">ENDPOINT</span> App
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-1 md:gap-8">
            {!isSignedIn && (
              <div className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20">
                <div className="text-lg">
                  <SignInButton mode="modal">
                    <button className="btn">
                      <h3 className="text-2xl font-bold">Login</h3>
                      <p>Click here to Login with Clerk! </p>Sign in
                    </button>
                  </SignInButton>
                </div>
              </div>
            )}
          </div>
          {isSignedIn && (
            <h1 className="text-5xl font-extrabold tracking-tight text-[hsl(280,100%,70%)]">
              Hello, {user.firstName}
            </h1>
          )}
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        </div>
      </main>
    </>
  );
};

export default Home;
